trigger:
- main  # Trigger pipeline on push to 'main' branch

pool:
  name: SelfHosted  # Use your self-hosted agent pool

variables:
  buildConfiguration: 'Release'

steps:
# Use .NET 8 SDK (Latest patch version)
- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    version: 8.0.204
    includePreviewVersions: false

# Restore NuGet packages
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '**/*.sln'

# Build the project
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# Run unit tests
- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'
