trigger:
- main  # Trigger pipeline on push to 'main' branch

pool:
  name: SelfHosted  # Use your self-hosted agent pool

variables:
  buildConfiguration: 'Release'

steps:
# Use .NET 8 SDK (Latest patch version)
- task: UseDotNet@2
  displayName: 'Use .NET 8 SDK'
  inputs:
    version: 8.0.204
    includePreviewVersions: false

# Restore NuGet packages
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '**/*.sln'

# Build the project
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**/*.sln'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# Run unit tests
- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# Publish the project
- task: DotNetCoreCLI@2
  displayName: 'Publish Application'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false

# Deploy to local IIS folder
- task: PowerShell@2
  displayName: 'Deploy to IIS'
  inputs:
    targetType: 'inline'
    script: |
      $source = "$(Build.ArtifactStagingDirectory)"
      $destination = "C:\inetpub\wwwroot\AzureTestApp"
      Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force

#Solution 1: Run the Agent as Administrator
#Your self-hosted agent needs elevated privileges to access the IIS directory. To do this:

#Open Services (services.msc) on your agent machine.

#Find your Azure Pipelines agent service.

#Right-click → Properties → switch to the Log On tab.

#Change it from Local System to a user account that:

#Has Administrator rights.

#Has write access to C:\inetpub\wwwroot.

#Then restart the agent service to apply the changes.